name: stylelint-declaration-block-no-ignored-properties
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-030-stylelint-declaration-block-no-ignored-properties.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-030-stylelint-declaration-block-no-ignored-properties.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-030-stylelint-declaration-block-no-ignored-properties
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    with:
      package: stylelint-declaration-block-no-ignored-properties
