name: next
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package.035-stylelint-media-use-custom-media.next.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package.035-stylelint-media-use-custom-media.next.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-035-stylelint-media-use-custom-media-next
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    with:
      package: stylelint-media-use-custom-media
      stylelint-version: stylelint/stylelint
