name: stylelint-less
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-less-d99.latest.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-less-d99.latest.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-stylelint-less-d99-latest
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: latest
    with:
      package: stylelint-less
      stylelint-version: stylelint@latest
      set-overrides-command: npm pkg set pnpm.overrides.stylelint
      install-command: pnpm install --no-frozen-lockfile
      list-installed-versions-command: pnpm list stylelint
      build-command: pnpm -r build
      test-command: pnpm -r test
