name: stylelint-value-no-unknown-custom-properties
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-value-no-unknown-custom-properties-2f3.next.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-value-no-unknown-custom-properties-2f3.next.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-stylelint-value-no-unknown-custom-properties-2f3-next
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: next
    with:
      package: stylelint-value-no-unknown-custom-properties
      stylelint-version: stylelint/stylelint
