name: stylelint-config-recommended-less
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-config-recommended-less-00b.latest.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-config-recommended-less-00b.latest.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-stylelint-config-recommended-less-00b-latest
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: latest
    with:
      package: stylelint-config-recommended-less
      stylelint-version: stylelint@latest
