name: Test Ecosystem

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        repository:
          - hudochenkov/stylelint-order
          - prettier/stylelint-prettier
          - stylelint-scss/stylelint-scss
        stylelint-version:
          - stylelint/stylelint
    steps:
      - name: Checkout ${{ matrix.repository }}
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install latest npm
        run: |
          npm install --global npm@latest
          echo "npm: $(npm --version)"

      - name: Install dependencies
        run: npm install

      - name: Install Stylelint from ${{ matrix.stylelint-version }}
        run: npm install --no-save --no-audit --verbose ${{ matrix.stylelint-version }}

      - name: Run test
        run: npm test
