name: stylelint-prettier
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-040-stylelint-prettier.latest.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-040-stylelint-prettier.latest.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-40-latest
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: latest
    with:
      package: stylelint-prettier
      stylelint-version: stylelint@latest
