name: Test stylelint-suitcss
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-046-stylelint-suitcss.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-046-stylelint-suitcss.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-046-stylelint-suitcss
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    with:
      package: stylelint-suitcss
