name: Test stylelint-config-idiomatic-order
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-011-stylelint-config-idiomatic-order.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-011-stylelint-config-idiomatic-order.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-011-stylelint-config-idiomatic-order
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    with:
      package: stylelint-config-idiomatic-order
