name: Test Ecosystem

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        # Based on the following search results:
        # - https://www.npmjs.com/search?q=keywords%3Astylelint-config&ranking=popularity
        # - https://www.npmjs.com/search?q=keywords%3Astylelint-plugin&ranking=popularity
        #
        # The following snippet on a browser dev console may be helpful to create this list.
        #
        #     [...document.querySelectorAll('a[href^="/package"][target="_self"]')].map(a => a.href.replace(/.+\/package\/(.+)$/, "- '$1'")).sort().join("\n")
        #
        package:
          # In alphabetical order
          - '@csstools/stylelint-at-risk'
          - '@csstools/stylelint-no-at-nest-rule'
          - '@csstools/stylelint-no-invalid-at-import-rules-when-bundling'
          - '@design-systems/stylelint-config'
          - '@double-great/stylelint-a11y'
          - '@jetbrains/stylelint-config'
          - '@mediamonks/stylelint-config'
          - '@namics/stylelint-bem'
          - '@o3r/stylelint-plugin'
          - '@primer/stylelint-config'
          - '@pro-vision/stylelint-config-pv'
          - '@ronilaukkarinen/stylelint-a11y'
          - '@shopify/stylelint-plugin'
          - '@so1ve/stylelint-config-basic'
          - '@springernature/stylelint-config'
          - '@stylistic/stylelint-config'
          - '@stylistic/stylelint-plugin'
          - '@wemake-services/stylelint-config-scss'
          - '@wordpress/stylelint-config'
          - 'stylelint-browser-compat'
          - 'stylelint-color-format'
          - 'stylelint-config-ali'
          - 'stylelint-config-astro'
          - 'stylelint-config-bod'
          - 'stylelint-config-clean-order'
          - 'stylelint-config-cloudfour'
          - 'stylelint-config-coldfront'
          - 'stylelint-config-concentric-order'
          - 'stylelint-config-css-modules'
          - 'stylelint-config-html'
          - 'stylelint-config-idiomatic-order'
          - 'stylelint-config-kyt'
          - 'stylelint-config-prestashop'
          - 'stylelint-config-property-sort-order-smacss'
          - 'stylelint-config-rational-order'
          - 'stylelint-config-rational-order-fix'
          - 'stylelint-config-recess-order'
          - 'stylelint-config-recommended'
          - 'stylelint-config-recommended-scss'
          - 'stylelint-config-recommended-vue'
          - 'stylelint-config-sass-guidelines'
          - 'stylelint-config-shopify'
          - 'stylelint-config-sky-uk'
          - 'stylelint-config-standard'
          - 'stylelint-config-standard-scss'
          - 'stylelint-config-standard-vue'
          - 'stylelint-config-styled-components'
          - 'stylelint-config-suitcss'
          - 'stylelint-config-taro-rn'
          - 'stylelint-config-twbs-bootstrap'
          - 'stylelint-config-wikimedia'
          - 'stylelint-config-xo'
          - 'stylelint-config-xo-scss'
          - 'stylelint-csstree-validator'
          - 'stylelint-declaration-block-no-ignored-properties'
          - 'stylelint-declaration-strict-value'
          - 'stylelint-define-config'
          - 'stylelint-file-max-lines'
          - 'stylelint-gamut'
          - 'stylelint-group-selectors'
          - 'stylelint-high-performance-animation'
          - 'stylelint-less'
          - 'stylelint-media-use-custom-media'
          - 'stylelint-no-browser-hacks'
          - 'stylelint-no-indistinguishable-colors'
          - 'stylelint-no-nested-media'
          - 'stylelint-no-px'
          - 'stylelint-no-restricted-syntax'
          - 'stylelint-no-unresolved-module'
          - 'stylelint-no-unsupported-browser-features'
          - 'stylelint-no-unused-selectors'
          - 'stylelint-number-z-index-constraint'
          - 'stylelint-order'
          - 'stylelint-performance-animation'
          - 'stylelint-plugin-defensive-css'
          - 'stylelint-plugin-logical-css'
          - 'stylelint-plugin-stylus'
          - 'stylelint-prettier'
          - 'stylelint-react-native'
          - 'stylelint-rem-over-px'
          - 'stylelint-rscss'
          - 'stylelint-scss'
          - 'stylelint-selector-bem-pattern'
          - 'stylelint-selector-no-empty'
          - 'stylelint-selector-pseudo-class-lvhfa'
          - 'stylelint-selector-tag-no-without-class'
          - 'stylelint-semantic-groups'
          - 'stylelint-stylus'
          - 'stylelint-suitcss'
          - 'stylelint-taro-rn'
          - 'stylelint-use-logical'
          - 'stylelint-use-logical-spec'
          - 'stylelint-use-nesting'
          - 'stylelint-value-list-box-shadow-inset-first'
          - 'stylelint-value-no-unknown-custom-properties'
          - 'stylelint-z-index-value-constraint'
        stylelint-version:
          - 'stylelint/stylelint'
          - 'stylelint@latest'
    steps:
      - name: Get repo info from ${{ matrix.package }}
        id: repo-info
        env:
          PACKAGE: ${{ matrix.package }}
        run: |
          url=$(npm repo --browser=false --json "${PACKAGE}" | jq -r '.url')
          echo "URL: ${url}"
          echo "url=${url}" >> "${GITHUB_OUTPUT}"

          fullname=$(echo "${url}" | sed -E 's/.*github.com\/([^/]+\/[^/]+).*/\1/')
          echo "Fullname: ${fullname}"
          echo "fullname=${fullname}" >> "${GITHUB_OUTPUT}"

          directory=$(npm view "${PACKAGE}" 'repository.directory')
          echo "Directory: ${directory}"
          echo "directory=${directory}" >> "${GITHUB_OUTPUT}"

          case "${PACKAGE}" in
            stylelint-browser-compat)
              echo "::warning ::The repository info is missing. Visit https://github.com/3846masa/stylelint-browser-compat"
              echo "url=https://github.com/3846masa/stylelint-browser-compat" >> "${GITHUB_OUTPUT}"
              echo "fullname=3846masa/stylelint-browser-compat" >> "${GITHUB_OUTPUT}"
              ;;
            stylelint-config-ali)
              echo "::warning ::The repository directory is missing. Visit ${url}"
              echo "directory=packages/stylelint-config-ali" >> "${GITHUB_OUTPUT}"
              ;;
          esac

      - name: Checkout ${{ steps.repo-info.outputs.fullname }}
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.repo-info.outputs.fullname }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install latest npm
        run: |
          npm install --global npm@latest
          echo "npm: $(npm --version)"

      - name: Install pnpm
        run: |
          npm install --global pnpm
          echo "pnpm: $(pnpm --version)"

      - name: Install yarn
        run: |
          npm install --global yarn
          echo "yarn: $(yarn --version)"

      - name: Install dependencies
        id: install-dependencies
        working-directory: ${{ steps.repo-info.outputs.directory }}
        env:
          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
        run: |
          if npm install --no-audit; then
            echo "passed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "::error ::The dependency installation failed. Visit ${PACKAGE_URL}"
          fi

      - name: Install Stylelint ${{ matrix.stylelint-version }}
        id: install-stylelint
        if: ${{ steps.install-dependencies.outputs.passed }}
        working-directory: ${{ steps.repo-info.outputs.directory }}
        env:
          STYLELINT_VERSION: ${{ matrix.stylelint-version }}
          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
        run: |
          if npm install --no-audit --no-save "${STYLELINT_VERSION}"; then
            echo "passed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "::error ::The Stylelint (${STYLELINT_VERSION}) installation failed. Visit ${PACKAGE_URL}"
          fi

      - name: Run build
        id: build
        if: ${{ steps.install-dependencies.outputs.passed && steps.install-stylelint.outputs.passed }}
        working-directory: ${{ steps.repo-info.outputs.directory }}
        env:
          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
        run: |
          if npm run build --if-present; then
            echo "passed=true" >> "${GITHUB_OUTPUT}"
          else
            echo "::error ::The build failed. Visit ${PACKAGE_URL}"
          fi

      - name: Run test
        id: test
        if: ${{ steps.install-dependencies.outputs.passed && steps.install-stylelint.outputs.passed && steps.build.outputs.passed }}
        working-directory: ${{ steps.repo-info.outputs.directory }}
        env:
          PACKAGE_URL: ${{ steps.repo-info.outputs.url }}
        run: |
          if ! npm test; then
            echo "::error ::The test failed. Visit ${PACKAGE_URL}"
          fi
