name: stylelint-declaration-block-no-ignored-properties
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-declaration-block-no-ignored-properties-a66.next.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-declaration-block-no-ignored-properties-a66.next.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-stylelint-declaration-block-no-ignored-properties-a66-next
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: next
    with:
      package: stylelint-declaration-block-no-ignored-properties
      stylelint-version: stylelint/stylelint
