name: stylelint-media-use-custom-media
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-media-use-custom-media-60a.next.yml
  pull_request:
    paths:
      - .github/workflows/test-package.yml
      - .github/workflows/test-package-stylelint-media-use-custom-media-60a.next.yml
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref
    }}-stylelint-media-use-custom-media-60a-next
  cancel-in-progress: true
jobs:
  test:
    uses: ./.github/workflows/test-package.yml
    name: next
    with:
      package: stylelint-media-use-custom-media
      stylelint-version: stylelint/stylelint
